---
title: "Saturation Vapour Pressure"
author: "M.Marchildon"
date: "27/09/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

## August-Roche-Magnus approximation [Pa]
> from pg.38 of Lu, N. and J.W. Godt, 2013. Hillslope Hydrology and Stability. Cambridge University Press. 437pp.) \

$$ 
  e_s=610.49 \cdot \exp\frac{17.625\cdot T_C}{T_C+243.04},
$$

Saturation Vapour Pressure ($e_s$) [Pa=N/m²], where $T_C$ is air temperature in degrees Celsius. Plotting this relationship between temperatures -30°C and 50°C (R²=1):


```{r esplot, echo=FALSE, warning=FALSE}
es.obs <- read.csv('saturationvapourpressure/es.csv',skip=1)

es.obs %>% ggplot() +
  theme(legend.title = element_blank(), legend.background = element_blank(), legend.position = c(.75,.25)) +
  geom_function(fun = function(x) 610.49*exp(17.625*x/(x+243.04)), aes(linewidth = 'Approximation')) +
  geom_point(aes(Temperature,saturation.vapour.pressure.over.liquid.water, size = 'Measured')) +
  scale_linewidth_manual(values = c('Approximation' = 1)) +
  labs(title="August-Roche-Magnus approximation",y="Saturation vapour pressure over liquid water [Pa]",x="Temperature [°C]") +
  xlim(c(-50,50)) +
  coord_flip()
```
